from toolkit import *
import random

if __name__ == '__main__':
    nls = [17 * 19, 23 * 47]
    for n in nls:
        bls = simplified_redundant(n)[1:]
        for b in bls:
            x = pow(b, n - 1, n)
            if 1 == x:
                print(n, 'is the pseudoprime of base', b)

    t = 30
    lst = [1, 2, 3]
    found = False
    while not found:
        n = randint(4)
        while len(str(n)) < 10:
            n = randint(4)
        # print('testing', n)
        for i in range(t):
            b = 2
            while gcd(b, n) != 1:
                b = randint(random.choice(lst))
            if 1 != pow(b, n - 1, n):
                break
            if i == t - 1:
                found = True
                print('Prime number generated by Fermat test is', n)
